/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;
import javax.swing.JOptionPane;

/**
 *
 * @author Okumura Rinzler
 */
public class frameGame extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    private int players = 0;
    protected final Game Mech = new Game();
    
    public frameGame() {
        initComponents();
        Mech.armarPreguntas();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        J1 = new javax.swing.JLabel();
        J2 = new javax.swing.JLabel();
        J3 = new javax.swing.JLabel();
        J4 = new javax.swing.JLabel();
        J1Score = new javax.swing.JLabel();
        J2Score = new javax.swing.JLabel();
        J3Score = new javax.swing.JLabel();
        J4Score = new javax.swing.JLabel();
        Next = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Question = new javax.swing.JTextArea();
        Dado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 450));
        setPreferredSize(new java.awt.Dimension(420, 350));
        setResizable(false);

        J1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        J1.setText("J1");

        J2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        J2.setText("J2");

        J3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        J3.setText("J3");

        J4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        J4.setText("J4");

        J1Score.setText("J1 Score");

        J2Score.setText("J2 Score");

        J3Score.setText("J3 Score");

        J4Score.setText("J4 Score");

        Next.setText("Siguiente!");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        Question.setEditable(false);
        Question.setColumns(20);
        Question.setRows(5);
        Question.setWrapStyleWord(true);
        Question.setAutoscrolls(false);
        jScrollPane1.setViewportView(Question);

        Dado.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        Dado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/misojos.jpg"))); // NOI18N
        Dado.setText("Dado");
        Dado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(J2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(J2Score, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(J4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(J3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(J3Score)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(J1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(J1Score))
                                .addGap(125, 125, 125)
                                .addComponent(Dado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(J4Score))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(J1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J1Score)
                        .addGap(30, 30, 30)
                        .addComponent(J2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J2Score)
                        .addGap(31, 31, 31)
                        .addComponent(J3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(J3Score)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(J4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Dado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(J4Score)
                .addGap(32, 32, 32)
                .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        Mech.score_update(J1Score,  J2Score,  J3Score,  J4Score,  Dado);
        if(Mech.ScoreCheck()==false) {
            dispose();
        }
        Mech.checkStateAndGoNext(J1,J2,J3,J4,J1Score,J2Score,J3Score,J4Score,Dado,Next,Question);
    }//GEN-LAST:event_NextActionPerformed

    private void DadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DadoActionPerformed
        Mech.dado_number(Dado, Question);
    }//GEN-LAST:event_DadoActionPerformed

    
    public void setPlayers(int p){
        this.players = p;
    } 
    
    public void setDadoIcon(){
        Dado.setIcon(null);
    }
    
    public void SetDadoText(String d){
        Dado.setText(d);
    }
    
    protected javax.swing.JButton Dado;
    protected javax.swing.JLabel J1;
    protected javax.swing.JLabel J1Score;
    protected javax.swing.JLabel J2;
    protected javax.swing.JLabel J2Score;
    protected javax.swing.JLabel J3;
    protected javax.swing.JLabel J3Score;
    protected javax.swing.JLabel J4;
    protected javax.swing.JLabel J4Score;
    protected javax.swing.JButton Next;
    protected javax.swing.JTextArea Question;
    protected javax.swing.JScrollPane jScrollPane1;
    
    
    public void setJ1(String j){
        J1.setText(j);
    }
    public void setJ2(String j){
        J2.setText(j);
    }
    public void setJ3(String j){
        J3.setText(j);
    }
    public void setJ4(String j){
        J4.setText(j);
    }
    public void setJ1Score(String j){
        J1Score.setText(j);
    }    
    public void setJ2Score(String j){
        J2Score.setText(j);
    }
    public void setJ3Score(String j){
        J3Score.setText(j);
    }
    public void setJ4Score(String j){
        J4Score.setText(j);
    } 
    
    public void setNextText(String t){
        Next.setText(t);
    }
    
    public void setNextQuestion(String t){
        Question.setText(t);
    }
    

}
