/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplocalculadoraframe;

import javax.swing.JOptionPane;

/**
 *
 * @author yojvn
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calculadora
     */        
    private String [] numeros = {"",""};
    private int control = 0;
    private metodosCalculadora metodos = new metodosCalculadora();
    private int opcion;
    public calculadora() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        butonOne = new javax.swing.JButton();
        butonTwo = new javax.swing.JButton();
        butonThree = new javax.swing.JButton();
        butonFour = new javax.swing.JButton();
        butonFive = new javax.swing.JButton();
        butonSix = new javax.swing.JButton();
        butonSeven = new javax.swing.JButton();
        butonEigth = new javax.swing.JButton();
        butonNine = new javax.swing.JButton();
        butonZero = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        suma = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        multiplicacion = new javax.swing.JButton();
        division = new javax.swing.JButton();
        sqrt = new javax.swing.JButton();
        igual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        butonOne.setFont(new java.awt.Font("Emulogic", 0, 24)); // NOI18N
        butonOne.setText("1");
        butonOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonOneActionPerformed(evt);
            }
        });

        butonTwo.setFont(new java.awt.Font("Emulogic", 0, 24)); // NOI18N
        butonTwo.setText("2");
        butonTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonTwoActionPerformed(evt);
            }
        });

        butonThree.setFont(new java.awt.Font("Emulogic", 0, 24)); // NOI18N
        butonThree.setText("3");
        butonThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonThreeActionPerformed(evt);
            }
        });

        butonFour.setFont(new java.awt.Font("Emulogic", 0, 24)); // NOI18N
        butonFour.setText("4");
        butonFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonFourActionPerformed(evt);
            }
        });

        butonFive.setFont(new java.awt.Font("Emulogic", 0, 24)); // NOI18N
        butonFive.setText("5");
        butonFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonFiveActionPerformed(evt);
            }
        });

        butonSix.setFont(new java.awt.Font("Emulogic", 0, 24)); // NOI18N
        butonSix.setText("6");
        butonSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonSixActionPerformed(evt);
            }
        });

        butonSeven.setFont(new java.awt.Font("Emulogic", 0, 24)); // NOI18N
        butonSeven.setText("7");
        butonSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonSevenActionPerformed(evt);
            }
        });

        butonEigth.setFont(new java.awt.Font("Emulogic", 0, 24)); // NOI18N
        butonEigth.setText("8");
        butonEigth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonEigthActionPerformed(evt);
            }
        });

        butonNine.setFont(new java.awt.Font("Emulogic", 0, 24)); // NOI18N
        butonNine.setText("9");
        butonNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonNineActionPerformed(evt);
            }
        });

        butonZero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        butonZero.setText("0");
        butonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonZeroActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        clear.setText("C");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(butonOne)
                        .addGap(33, 33, 33)
                        .addComponent(butonTwo)
                        .addGap(28, 28, 28)
                        .addComponent(butonThree))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butonFour)
                            .addComponent(butonSeven))
                        .addGap(33, 33, 33)
                        .addComponent(butonFive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butonSix))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(butonEigth))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(butonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(butonNine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butonOne)
                    .addComponent(butonTwo)
                    .addComponent(butonThree))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butonFour)
                    .addComponent(butonFive)
                    .addComponent(butonSix))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butonSeven)
                    .addComponent(butonEigth)
                    .addComponent(butonNine))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butonZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Emulogic", 0, 48)); // NOI18N
        jLabel1.setText("0");

        suma.setFont(new java.awt.Font("Emulogic", 0, 24)); // NOI18N
        suma.setText("+");
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });

        resta.setFont(new java.awt.Font("Emulogic", 0, 24)); // NOI18N
        resta.setText("-");
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });

        multiplicacion.setFont(new java.awt.Font("Emulogic", 0, 24)); // NOI18N
        multiplicacion.setText("*");
        multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacionActionPerformed(evt);
            }
        });

        division.setFont(new java.awt.Font("Emulogic", 0, 24)); // NOI18N
        division.setText("/");
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });

        sqrt.setText("Raiz");
        sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(suma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(multiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resta))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(sqrt)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suma)
                    .addComponent(resta))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(multiplicacion)
                    .addComponent(division))
                .addGap(18, 18, 18)
                .addComponent(sqrt)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        igual.setFont(new java.awt.Font("Emulogic", 0, 24)); // NOI18N
        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butonOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonOneActionPerformed
        numberPush(1,control);
    }//GEN-LAST:event_butonOneActionPerformed

    private void butonTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonTwoActionPerformed
        numberPush(2,control);
    }//GEN-LAST:event_butonTwoActionPerformed

    private void butonThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonThreeActionPerformed
        numberPush(3,control);
    }//GEN-LAST:event_butonThreeActionPerformed

    private void butonFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonFourActionPerformed
        numberPush(4,control);
    }//GEN-LAST:event_butonFourActionPerformed

    private void butonFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonFiveActionPerformed
        numberPush(5,control);
    }//GEN-LAST:event_butonFiveActionPerformed

    private void butonSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonSixActionPerformed
        numberPush(6,control);
    }//GEN-LAST:event_butonSixActionPerformed

    private void butonSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonSevenActionPerformed
        numberPush(7,control);
    }//GEN-LAST:event_butonSevenActionPerformed

    private void butonEigthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonEigthActionPerformed
        numberPush(8,control);
    }//GEN-LAST:event_butonEigthActionPerformed

    private void butonNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonNineActionPerformed
        numberPush(9,control);
    }//GEN-LAST:event_butonNineActionPerformed

    private void butonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonZeroActionPerformed
        numberPush(0,control);
    }//GEN-LAST:event_butonZeroActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
        control = 1;
        opcion = 0;
    }//GEN-LAST:event_sumaActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
        control = 1;
        opcion = 1;        
    }//GEN-LAST:event_restaActionPerformed

    private void multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacionActionPerformed
        control = 1;
        opcion = 2;        
    }//GEN-LAST:event_multiplicacionActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
        control = 1;
        opcion = 3;        
    }//GEN-LAST:event_divisionActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        igual(opcion);
        control = 0;
        numeros[0]="";
        numeros[1]="";
        
    }//GEN-LAST:event_igualActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        clear();
        
    }//GEN-LAST:event_clearActionPerformed

    private void sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtActionPerformed
        
    }//GEN-LAST:event_sqrtActionPerformed
    
   public void numberPush(int number, int pos){
       numeros [pos] += number;
       jLabel1.setText(numeros[pos]);
   }
   
   public void clear (){
       jLabel1.setText("");
       numeros[0]="";
       numeros[1]="";
       control = 0;
   }
   
   public void igual (int opcion){
       if("".equals(numeros[0]) || "".equals(numeros[1])){
           JOptionPane.showMessageDialog(null, "Escriba los Numeros Primero!");
           jLabel1.setText("");
       } else{
       String resultado;
       switch (opcion){
           case 0 : 
               resultado = Long.toString(metodos.suma(Long.parseLong(numeros[0]),Long.parseLong(numeros[1])));
               jLabel1.setText(resultado);
               break;
           case 1 : 
               resultado = Long.toString(metodos.resta(Long.parseLong(numeros[0]),Long.parseLong(numeros[1])));
               jLabel1.setText(resultado);
               break;
           case 2 : 
               resultado = Long.toString(metodos.mult(Long.parseLong(numeros[0]),Long.parseLong(numeros[1])));
               jLabel1.setText(resultado);
               break;
           case 3 : 
               resultado = Double.toString(metodos.div(Integer.parseInt(numeros[0]),Integer.parseInt(numeros[1])));
               jLabel1.setText(resultado);
               break;
           default : System.out.println("gg");
               break;
       }
        
        
        
              
    }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonEigth;
    private javax.swing.JButton butonFive;
    private javax.swing.JButton butonFour;
    private javax.swing.JButton butonNine;
    private javax.swing.JButton butonOne;
    private javax.swing.JButton butonSeven;
    private javax.swing.JButton butonSix;
    private javax.swing.JButton butonThree;
    private javax.swing.JButton butonTwo;
    private javax.swing.JButton butonZero;
    private javax.swing.JButton clear;
    private javax.swing.JButton division;
    private javax.swing.JButton igual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton multiplicacion;
    private javax.swing.JButton resta;
    private javax.swing.JButton sqrt;
    private javax.swing.JButton suma;
    // End of variables declaration//GEN-END:variables
}
